# The Docker image that will be used to build your app
image: node:22.0.0

before_script:
  # Functions that should be executed before the build script is run
  - npm install -g pnpm
  - pnpm install 
  - pnpm add sharp 
  - pnpm exec playwright install 
  - pnpm exec playwright install-deps  

pages:
  script:
    # Specify the steps involved to build your app here
    - pnpm build
    - rm -rf public/*
    - mv dist/* public/
    
  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public

  only:
    # Trigger a new build and deploy only when there is a push to the
    # below branch(es)
    - master
